services:
  - type: web
    name: glass-order-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: cd apps/backend && pnpm render:build
    startCommand: cd apps/backend && pnpm render:start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: glass-order-db
          property: connectionString
      - key: GROQ_API_KEY
        sync: false  # Set manually in dashboard
      - key: OPENAI_API_KEY
        sync: false  # Set manually in dashboard
      - key: ENABLE_VOICE_FEATURES
        value: true
      - key: VOICE_SESSION_TIMEOUT
        value: 300000
      - key: ENABLE_CONTINUOUS_LISTENING
        value: true
      - key: VOICE_ACTIVITY_THRESHOLD
        value: 0.3
      - key: SILENCE_TIMEOUT_MS
        value: 1500
      - key: MAX_CONVERSATION_LENGTH
        value: 30
      - key: INTERRUPT_THRESHOLD
        value: 0.5
      - key: AI_RESPONSE_STYLE
        value: conversational_telephonic
      - key: ENABLE_FILLER_WORDS
        value: true
      - key: ENABLE_THINKING_SOUNDS
        value: true
      - key: PDF_STORAGE_PATH
        value: ./temp/pdfs
      - key: PDF_CLEANUP_INTERVAL
        value: 3600000
      - key: CLIENT_URL
        value: https://your-frontend-url.onrender.com
      - key: DISABLE_SWAGGER
        value: false  # Enable Swagger in production for API documentation
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: true  # Skip Chrome download during deployment

databases:
  - name: glass-order-db
    databaseName: glass_order_production
    user: glass_order_user
