name: Deploy to Vercel

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Clean install dependencies
        run: |
          # Clean any existing node_modules and lockfile issues
          rm -rf node_modules apps/*/node_modules
          pnpm install --no-frozen-lockfile

      - name: Generate Prisma client
        run: |
          cd apps/backend
          pnpm db:generate

      - name: Build backend
        run: |
          cd apps/backend
          pnpm run build

      - name: Build frontend
        run: |
          cd apps/frontend
          pnpm run build

      - name: Deploy Frontend to Vercel
        uses: vercel/action@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./apps/frontend
          vercel-args: '--prod'

      - name: Deploy Backend to Vercel
        uses: vercel/action@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_BACKEND_PROJECT_ID }}
          working-directory: ./apps/backend
          vercel-args: '--prod'
